# go run github.com/go-task/task/v3/cmd/task@latest deps
version: '3'
dotenv: ['.env']
tasks:
  default:
    cmds:
      - docker compose up --wait
      - go run github.com/cosmtrek/air@latest
  
  pre:
    deps: [templ, css, js]
  
  templ:
    cmds:
      - go run github.com/a-h/templ/cmd/templ@latest generate

  css:
    cmds:
      - npm run css

  js:
    cmds:
      - npm run js

  deps:
    cmds:
      - asdf install
      - npm install
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/cosmtrek/air@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/amacneil/dbmate@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
      - asdf reshim golang

  sql:
    cmds:
      - go run github.com/amacneil/dbmate@latest --schema-file=internal/db/schema.sql --migrations-dir=internal/db/migrations dump
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc@latest generate

  post:
    cmds:
      - docker compose down
  
  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2 run -E gosec -E gofmt -E goimports -E sloglint
      - go vet ./...
  
  tidy:
    cmds:
      - go fmt ./...
      - templ fmt .
      - go mod tidy -v

  build:
    cmds:
      - npm install
      - task: pre
      - task: lint
      - task: test
      - go build ./cmd/rhizome

  run:
    cmds:
      - ./rhizome

  clean:
    cmds:
      - rm ./rhizome

  reset:
    cmds:
      - go run github.com/amacneil/dbmate@latest --no-dump-schema --migrations-dir=internal/db/migrations rollback
      - go run github.com/amacneil/dbmate@latest --no-dump-schema --migrations-dir=internal/db/migrations up

  psql:
    cmds:
      - psql $DATABASE_URL

  seed:
    cmds:
      - go run ./cmd/seed

  test:
    cmds:
      - go test -short ./...

  integration:
    cmds:
      - go test ./...
