version: '3'
dotenv: ['.env']
tasks:
  default:
    cmds:
      - npm install
      - docker compose up --wait
      - go run github.com/cosmtrek/air@latest
  
  pre:
    deps: [templ, css, js]
  
  templ:
    cmds:
      - go run github.com/a-h/templ/cmd/templ@latest generate

  css:
    cmds:
      - npx tailwindcss -i ./frontend/app.css --minify -o ./internal/assets/static/app.css

  js:
    cmds:
      - npx esbuild ./frontend/app.js --bundle --minify --outfile=./internal/assets/static/app.js

  sql:
    cmds:
      - go run github.com/amacneil/dbmate@latest --schema-file=internal/db/schema.sql --migrations-dir=internal/db/migrations dump
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc@latest generate

  post:
    cmds:
      - docker compose down
  
  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2 run
      - go vet ./...
  
  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy -v

  build:
    cmds:
      - npm install
      - task: pre
      - task: lint
      - task: test
      - go build ./cmd/rhizome

  reset:
    cmds:
      - go run github.com/amacneil/dbmate@latest --no-dump-schema --migrations-dir=internal/db/migrations rollback
      - go run github.com/amacneil/dbmate@latest --no-dump-schema --migrations-dir=internal/db/migrations up

  psql:
    cmds:
      - psql $DATABASE_URL

  seed:
    cmds:
      - go run ./cmd/seed

  test:
    cmds:
      - go test -short ./...

  integration:
    cmds:
      - go test ./...
