name: build
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          cache: false
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - run: go run github.com/go-task/task/v3/cmd/task@latest build